### PR TITLE
Update build.gradle

### PR DESCRIPTION
**Pull request by nadermkhan**
Added missing dependencies.
Dependencies for:

1) Commons Codec Library
2) Biometrics Library
3) Crypto Library
4) Androidx Annotation Library

 No need to download each time user create a project.

### CODE REVIEW

**Comment by nadermkhan** [comment]
Fixed conflict with alpha version dependency of Biometrics.

**Comment by Deenu488** [comment]
What is the use of this dependencies, they are not required

**Comment by nadermkhan** [comment]
They are not required, but sometimes we need them for implementation like

Crypto used for EncryptedSharedPrerference
Biometrics for ensuring that if it's phone owner
Annotation is badly required for some projects

it'll be better if we don't need to download these each time we will create a new project

**Comment by Deenu488** [comment]
@nadermkhan It is not required in the project, but If you want to add implementation libraries in project (templates)
You need to update templates

**Pull request closed without merging**
