### PR TITLE
feat: Update Libraries

### PR DESCRIPTION
**Pull request by trindadedev13**
* fix(deps): update dependency androidx.lifecycle:lifecycle-viewmodel to v2.8.4

* fix(deps): update dependency androidx.preference:preference to v1.2.1

* fix(deps): update dependency javax.xml.bind:jaxb-api to v2.3.1

* chore(deps): update dependency gradle to v8.10

* fix(deps): update dependency androidx.fragment:fragment to v1.8.2

* fix(deps): update dependency androidx.test.ext:junit to v1.2.1

* fix(deps): update dependency androidx.viewpager2:viewpager2 to v1.1.0

* fix(deps): update dependency com.android.tools.build:apksig to v8.6.0

* fix(deps): update dependency com.github.bumptech.glide:glide to v4.16.0

* fix(deps): update dependency com.github.javaparser:javaparser-core to v3.26.1

* fix(deps): update dependency com.google.auto.value:auto-value-annotations to v1.11.0

* fix(deps): update dependency com.google.testing.compile:compile-testing to v0.21.0

* fix(deps): update dependency commons-io:commons-io to v2.16.1

* fix(deps): update dependency me.xdrop:fuzzywuzzy to v1.4.0

* fix(deps): update dependency org.jsoup:jsoup to v1.18.1

* fix(deps): update junit5 monorepo to v5.11.0

* chore(deps): update actions/checkout action to v4

* chore(deps): update actions/setup-java action to v4

* chore(deps): update actions/upload-artifact action to v4

* fix(deps): update dependency com.android.tools:annotations to v31

* fix(deps): update dependency com.android.tools:desugar_jdk_libs to v2

* fix(deps): update dependency com.google.guava:guava to v33

* fix(deps): update dependency com.h2database:h2 to v2

* fix(deps): update dependency org.jetbrains:annotations to v24

* fix(deps): update dependency org.mockito:mockito-core to v5

* fix(deps): update kotlin monorepo to v2

* Update dependency junit:junit to v4.13.2

* Update dependency androidx.core:core to v1.13.1

* Update dependency androidx.lifecycle:lifecycle-viewmodel-ktx to v2.8.4

* Update dependency androidx.annotation:annotation to v1.8.2

* Update dependency androidx.fragment:fragment-testing to v1.8.2

* Update dependency androidx.test.espresso:espresso-core to v3.6.1

* Update dependency com.android.tools.build:gradle to v8.6.0

* Update dependency com.android.tools:r8 to v8.5.35

* Update dependency com.google.truth:truth to v1.4.4

* feat: workflow to delete runs

* fix: ```SUPER_TOKEN``` not found

* fix(deps): update dependency org.robolectric:robolectric to v4.13

* fix(deps): update dependency com.google.android.material:material to v1.12.0

* fix(deps): update dependency com.google.code.gson:gson to v2.11.0

* fix(deps): update dependency org.antlr:antlr4-runtime to v4.13.2

---------

### CODE REVIEW

**Comment by trindadedev13** [comment]
I didn't merge all the PRs, just the ones that were successful in the build.

**Comment by Deenu488** [comment]
Thankyou ♥️

**Comment by trindadedev13** [comment]
strange that release builds are not working 🤔

**Comment by Deenu488** [comment]
Yeah

**Pull request merged**
